spring.application.name=support-system

# Banco de dados 
spring.datasource.url=jdbc:postgresql://ep-weathered-mud-an83q202.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DAR4OzBU5yrj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=3cF8kP2mNqRtZvXwYhJdLbUgAeOiSuWnTjByCpDkMvQrHfGlEs7a9x1z4n6o0p
jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200

# Servidor
server.port=8080
